name: CI
on: push
jobs:
  Ruby_2_7:
    runs-on: ubuntu-latest
    container: ruby:2.7
    name: Ruby 2.7
    steps:
      - uses: actions/checkout@v1
      - run: gem install bundle
      - run: bundle
      - run: bundle exec rake

  Ruby_2_6:
    runs-on: ubuntu-latest
    container: ruby:2.6
    name: Ruby 2.6
    steps:
      - uses: actions/checkout@v1
      - run: gem install bundle
      - run: bundle
      - run: bundle exec rake

  Lambda_Ruby_2_7:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-ruby2.7
    name: Lambda Ruby 2.7
    steps:
      - uses: actions/checkout@v1
      - run: gem install bundle
      - run: bundle
      - run: bundle exec rake

  All:
    runs-on: ubuntu-latest
    needs:
      - Ruby_2_7
      - Ruby_2_6
      - Lambda_Ruby_2_7
    steps:
      - run: echo ok
